ERROR_MAP = {
    'AccessDenied': 'Permission denied. You do not have access to perform this action.',
    'NoSuchBucket': 'The specified bucket does not exist.',
    'NoSuchKey': 'The specified file or object does not exist.',
    'BucketAlreadyExists': 'The bucket name you tried to create already exists.',
    'BucketAlreadyOwnedByYou': 'You already own this bucket.',
    'InvalidBucketName': 'The bucket name provided is not valid.',
    'InvalidObjectState': 'The operation is not valid for the object’s current state.',
    'InvalidAccessKeyId': 'The provided access key ID does not exist.',
    'SignatureDoesNotMatch': 'The request signature we calculated does not match the signature you provided.',
    'SlowDown': 'You are sending too many requests too quickly. Please slow down.',
    'InternalError': 'The server encountered an internal error. Please try again later.',
    'ServiceUnavailable': 'The service is currently unavailable. Please try again later.',
    'IncompleteSignature': 'The request signature was incomplete or incorrect.',
    'InvalidArgument': 'The argument provided was invalid.',
    'InvalidRequest': 'The request made was invalid.',
    'MalformedXML': 'The XML provided in the request is malformed or invalid.',
    'RequestTimeout': 'The request timed out. Please try again.',
    'RequestTimeTooSkewed': 'The difference between the request time and the server’s time is too large.',
    'ExpiredToken': 'The provided token has expired.',
    'NoSuchUpload': 'The specified multipart upload does not exist.',
    'EntityTooSmall': 'The provided entity is too small.',
    'EntityTooLarge': 'The provided entity is too large.',
    'TooManyBuckets': 'You have attempted to create more buckets than allowed.',
    'BadRequest': 'The request could not be understood or was missing required parameters.',
    'MissingContentLength': 'The request did not include the content length header.',
    'InvalidContentLength': 'The content length specified is invalid.',
    'PreconditionFailed': 'A precondition specified in the request was not met.',
}

DEFAULT_ERROR_MESSAGE = 'An unknown error occurred. Please contact support if the problem persists.'
